// Request contracts checked against backend routes, independent of the operation registry.
export const cnpj = "12ABC34501DE35";
export const contracts = [
  [
    "lookup_cnpj",
    { cnpj: "12.abc.345/01de-35" },
    "lookup",
    ["12.abc.345/01de-35"],
    `/api/cnpj/${cnpj}`,
    {},
  ],
  [
    "list_filiais",
    { cnpj, per_page: 200, page: 200, uf: "sp", q: "Centro" },
    "filiais",
    [cnpj, { perPage: 200, page: 200, uf: "sp", q: "Centro" }],
    `/api/cnpj/${cnpj}/filiais`,
    { per_page: "200", page: "200", uf: "SP", q: "Centro" },
  ],
  [
    "search_companies",
    { query: " padaria ", per_page: 5 },
    "search",
    [" padaria ", { perPage: 5 }],
    "/api/search",
    { q: "padaria", page: "1", per_page: "5" },
  ],
  [
    "companies_by_owner",
    { name: "Maria Silva", cpf: "123456", exclude: "12ABC345" },
    "companiesByOwner",
    ["Maria Silva", { cpf: "123456", exclude: "12ABC345" }],
    "/api/socio/empresas",
    { nome: "Maria Silva", cpf: "123456", exclude: "12ABC345", limit: "20" },
  ],
  [
    "owner_companies_summary",
    { name: "Maria Silva" },
    "ownerCompaniesSummary",
    ["Maria Silva"],
    "/api/socio/empresas-resumo",
    { nome: "Maria Silva", limit: "20" },
  ],
  [
    "owner_summaries_batch",
    { items: [{ nome: "Maria Silva", cpf: "123456" }], exclude: "12ABC345" },
    "ownerSummariesBatch",
    [[{ nome: "Maria Silva", cpf: "123456" }], { exclude: "12ABC345" }],
    "/api/socio/empresas-resumo/batch",
    {},
    {
      items: [{ nome: "Maria Silva", cpf: "123456" }],
      exclude: "12ABC345",
      limit: 20,
    },
  ],
  [
    "companies_at_same_address",
    { cep: "01310-100", logradouro: "PAULISTA", numero: "100", limit: 100 },
    "companiesAtSameAddress",
    ["01310-100", "PAULISTA", "100", { limit: 100 }],
    "/api/endereco/empresas",
    { cep: "01310100", logradouro: "PAULISTA", numero: "100", limit: "100" },
  ],
  [
    "companies_by_contact",
    { ddd: "11", telefone: "99998888", exclude: "12ABC345" },
    "companiesByContact",
    [{ ddd: "11", telefone: "99998888", exclude: "12ABC345" }],
    "/api/contato/empresas",
    { ddd: "11", telefone: "99998888", exclude: "12ABC345", limit: "20" },
  ],
  [
    "participations",
    { cnpj, limit: 100 },
    "participations",
    [cnpj, { limit: 100 }],
    `/api/participacoes/${cnpj}`,
    { limit: "100" },
  ],
  [
    "control_tree",
    { cnpj },
    "controlTree",
    [cnpj],
    `/api/controle/${cnpj}`,
    {},
  ],
  [
    "common_owners",
    { cnpjs: [cnpj, "18236120000158"], modo: "sobreposicao", min_empresas: 2 },
    "commonOwners",
    [[cnpj, "18236120000158"], { modo: "sobreposicao", min_empresas: 2 }],
    "/api/socios-comum",
    {
      cnpjs: [cnpj, "18236120000158"],
      modo: "sobreposicao",
      min_empresas: "2",
    },
  ],
  [
    "advanced_search",
    {
      uf: "sp,rj",
      mei: false,
      municipio_codigo: "7107",
      capital_min: 0,
      nome_empresa: "Teste",
      com_email: true,
      telefone: "+55 11 99999-8888",
      cep: "01310-100",
      numero: "100",
    },
    "advancedSearch",
    [
      {
        uf: "sp,rj",
        mei: false,
        municipio_codigo: "7107",
        capital_min: 0,
        nome_empresa: "Teste",
        com_email: true,
        telefone: "+55 11 99999-8888",
        cep: "01310-100",
        numero: "100",
      },
    ],
    "/api/busca-avancada",
    {
      uf: "SP,RJ",
      mei: "false",
      municipio_codigo: "7107",
      capital_min: "0",
      nome_empresa: "Teste",
      com_email: "true",
      telefone: "+55 11 99999-8888",
      cep: "01310100",
      numero: "100",
      page: "1",
      per_page: "20",
    },
  ],
  [
    "competitors",
    { cnpj },
    "competitors",
    [cnpj],
    `/api/concorrentes/${cnpj}`,
    {},
  ],
  [
    "person_profile",
    { nome: "Maria Silva", cpf: "123456" },
    "personProfile",
    ["Maria Silva", { cpf: "123456" }],
    "/api/pessoa/raio-x",
    { nome: "Maria Silva", cpf: "123456" },
  ],
  [
    "search_owners",
    { nome: "Maria Silva", municipio_codigo: "7107", page: 25 },
    "searchOwners",
    [{ nome: "Maria Silva", municipio_codigo: "7107", page: 25 }],
    "/api/socios/busca",
    {
      nome: "Maria Silva",
      municipio_codigo: "7107",
      page: "25",
      per_page: "20",
    },
  ],
  [
    "autocomplete_owners",
    { q: "Maria", limit: 15 },
    "autocompleteOwners",
    ["Maria", { limit: 15 }],
    "/api/socios/autocomplete",
    { q: "Maria", limit: "15" },
  ],
  [
    "leads",
    {
      uf: "sp",
      municipio_codigo: "7107",
      data_abertura_min: "2026-01-01",
      data_abertura_max: "2026-09-30",
      com_email: false,
      idade_max: 2,
    },
    "leads",
    [
      {
        uf: "sp",
        municipio_codigo: "7107",
        data_abertura_min: "2026-01-01",
        data_abertura_max: "2026-09-30",
        com_email: false,
        idade_max: 2,
      },
    ],
    "/api/leads",
    {
      uf: "SP",
      municipio_codigo: "7107",
      data_abertura_min: "2026-01-01",
      data_abertura_max: "2026-09-30",
      com_email: "false",
      idade_max: "2",
      page: "1",
      per_page: "20",
    },
  ],
  [
    "companies_by_city",
    { uf: "SP", municipio: "7107", bairro: "Centro" },
    "companiesByCity",
    [{ uf: "SP", municipio: "7107", bairro: "Centro" }],
    "/api/empresas-cidade",
    {
      uf: "SP",
      municipio: "7107",
      bairro: "Centro",
      page: "1",
      per_page: "50",
    },
  ],
  [
    "corporate_group",
    { cnpj },
    "corporateGroup",
    [cnpj],
    `/api/intelligence/grupo/${cnpj}`,
    {},
  ],
  [
    "red_flags",
    { cnpj },
    "redFlags",
    [cnpj],
    `/api/intelligence/red-flags/${cnpj}`,
    {},
  ],
  [
    "ownership_network",
    { q: "Maria Silva", cpf: "123456" },
    "ownershipNetwork",
    ["Maria Silva", { cpf: "123456" }],
    "/api/intelligence/rede",
    { q: "Maria Silva", cpf: "123456" },
  ],
  [
    "compliance_summary",
    { cnpj },
    "complianceSummary",
    [cnpj],
    `/api/compliance/resumo/${cnpj}`,
    {},
  ],
  [
    "compliance_dossier",
    { cnpj },
    "complianceDossier",
    [cnpj],
    `/api/compliance/dossie/${cnpj}`,
    {},
  ],
  [
    "active_debt",
    { cnpj },
    "activeDebt",
    [cnpj],
    `/api/compliance/divida-ativa/${cnpj}`,
    {},
  ],
  [
    "cnae_stats",
    { codigo: "6201-5/01" },
    "cnaeStats",
    ["6201-5/01"],
    "/api/cnae/6201501/stats",
    {},
  ],
  ["list_cnaes", {}, "listCnaes", [], "/api/cnaes", {}],
  [
    "cnae_catalog",
    { secao: "j" },
    "cnaeCatalog",
    ["j"],
    "/api/cnaes/catalog",
    { secao: "J" },
  ],
  ["cnae_hub_summary", {}, "cnaeHubSummary", [], "/api/cnaes/hub-summary", {}],
  [
    "search_cnaes",
    { q: "software" },
    "searchCnaes",
    ["software"],
    "/api/cnaes/search",
    { q: "software", limit: "10" },
  ],
  [
    "search_municipalities",
    { q: "São Paulo", uf: "sp" },
    "searchMunicipalities",
    ["São Paulo", { uf: "sp" }],
    "/api/municipios/search",
    { q: "São Paulo", uf: "SP", limit: "15" },
  ],
  [
    "municipalities_by_uf",
    { uf: "sp" },
    "municipalitiesByUf",
    ["sp"],
    "/api/municipios-por-uf",
    { uf: "SP" },
  ],
  ["services_catalog", {}, "servicesCatalog", [], "/api/servicos/catalog", {}],
  [
    "search_services",
    { servico: "encanador", uf: "SP", municipio_codigo: "7107", sem_mei: true },
    "searchServices",
    [
      {
        servico: "encanador",
        uf: "SP",
        municipio_codigo: "7107",
        sem_mei: true,
      },
    ],
    "/api/servicos",
    {
      servico: "encanador",
      uf: "SP",
      municipio_codigo: "7107",
      sem_mei: "true",
      page: "1",
      per_page: "20",
    },
  ],
  [
    "panorama_overview",
    { sem_mei: true },
    "panoramaOverview",
    [{ sem_mei: true }],
    "/api/panorama/overview",
    { sem_mei: "true" },
  ],
  [
    "panorama_year",
    { year: 2024, sem_mei: true },
    "panoramaYear",
    [2024, { sem_mei: true }],
    "/api/panorama/year/2024",
    { sem_mei: "true" },
  ],
  [
    "panorama_alphanumeric",
    { year: 2026 },
    "panoramaAlphanumeric",
    [2026],
    "/api/panorama/alfanumericos/2026",
    {},
  ],
  [
    "panorama_catalog",
    { edicao: "0123456789abcdef" },
    "panoramaCatalog",
    ["0123456789abcdef"],
    "/api/panorama/catalog",
    { edicao: "0123456789abcdef" },
  ],
  [
    "panorama_report",
    { periodo: "202609", uf: "sp", recorte: "nao_mei", tema: "tecnologia" },
    "panoramaReport",
    ["202609", { uf: "sp", recorte: "nao_mei", tema: "tecnologia" }],
    "/api/panorama/report/202609",
    { uf: "SP", recorte: "nao_mei", tema: "tecnologia" },
  ],
  [
    "panorama_report_csv",
    { periodo: "2026", tabela: "municipios" },
    "panoramaReportCsv",
    ["2026", { tabela: "municipios" }],
    "/api/panorama/report/2026/csv",
    { uf: "BR", recorte: "todos", tabela: "municipios" },
  ],
  [
    "panorama_revisions",
    { periodo: "202609" },
    "panoramaRevisions",
    ["202609"],
    "/api/panorama/report/202609/revisions",
    {},
  ],
];
